spring:
  application:
    name: super-board

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3305/super_board
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  redis:
    host: localhost
    port: 6379
    password: ""

  data:
    mongodb:
      host: localhost
      port: 27017
      database: super_board

cloud:
  aws:
    s3:
      bucket: <????>
    stack.auto: false
    region.static: ap-northeast-2
    credentials:
      access-key: <???? accessKey>
      secret-key: <???? secretKey>

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html